feat(pack): add prisma language pack
AstroNvim/astrocommunity pull request #111
Opened 2023-03-31 20:07 UTC by 20k-ultra

2023-04-01 12:57 UTC, taskylizard approved these changes

2023-04-01 13:15 UTC, mehalter reviewed
Could you please format the code with `stylua` to pass the tests?

2023-04-01 13:18 UTC, mehalter requested changes
Small code change but that and stylua and we can get this merged! Thanks for this contribution!

2023-04-01 13:18 UTC, mehalter commented on lua/astrocommunity/pack/prisma/prisma.lua
> +      utils.list_insert_unique(opts.ensure_installed, { "prisma" })
```suggestion
      utils.list_insert_unique(opts.ensure_installed, "prisma")
```

2023-04-02 03:59 UTC, mehalter approved these changes
LGTM

2023-04-02 04:00 UTC, merged