fix(conform-nvim): fix formatters_by_ft definitions
AstroNvim/astrocommunity pull request #1129
Opened 2024-07-24 21:51 UTC by lucazz

## 📑 Description

As requested by @Uzaaft on #1127 #1128, I'm merging all changes in a single PR.

This PR updates stevearc/conform.nvim's setup, addressing the deprecation warning that comes up when opening any yaml file while using the yaml pack:
```
deprecated[conform]: The nested {} syntax to run the first formatter has been replaced by the stop_after_first option (see :help conform.format).
Support for the old syntax will be dropped on 2025-01-01.
```

2024-07-24 22:50 UTC, Uzaaft commented
@lucazz I’m about to head to bed so I cant deep dive into it, but based upon the warning you have this seem wrong.

2024-07-25 07:24 UTC, mehalter requested changes
This is incorrect, all of them should be 

```lua
{ "prettierd", "prettier", stop_after_first = true }
```

2024-07-25 12:39 UTC, Uzaaft commented
@lucazz  Why did you add it to the places where it's not needed?

2024-07-25 12:40 UTC, Uzaaft commented
Danke Danke

2024-07-25 13:03 UTC, mehalter requested changes

2024-07-25 13:03 UTC, mehalter commented on lua/astrocommunity/pack/go/init.lua
> +        go = { "goimports", "gofumpt", stop_after_first = true },
```suggestion
        go = { "goimports", "gofumpt" },
```
This is incorrect

2024-07-25 13:03 UTC, mehalter commented on lua/astrocommunity/pack/markdown/init.lua
> +        markdown = { "prettierd", "prettier" },
```suggestion
        markdown = { "prettierd", "prettier", stop_after_first = true },
```

This needs it

2024-07-25 13:03 UTC, mehalter commented on lua/astrocommunity/pack/python-ruff/init.lua
> +        python = { "ruff_organize_imports", "ruff_format", stop_after_first = true },
```suggestion
        python = { "ruff_organize_imports", "ruff_format" },
```

This is incorrect

2024-07-25 13:03 UTC, mehalter commented on lua/astrocommunity/pack/python/init.lua
> +        python = { "isort", "black", stop_after_first = true },
```suggestion
        python = { "isort", "black" },
```

Not this one

2024-07-25 13:07 UTC, mehalter approved these changes
Ok, I think this looks correct now, thanks! Just to clarify why the previous ones were incorrect. The nested structure indicated when to only stop at the first. The ones that were not previously nested indicated _multiple_ formatters so we very much do not want them to stop at the first

2024-07-25 13:08 UTC, merged