fix(go): automatically install gofumpt and goimports
AstroNvim/astrocommunity pull request #1162
Opened 2024-08-16 21:23 UTC by pgr0ss

## 📑 Description

The go configuration tells conform to use these tools for formatting, but they were not automatically installed. This fix adds them to the mason-tool-installer list so they will be installed with the rest of the go tools.

## ℹ Additional Information

These tools are referenced here:
https://github.com/AstroNvim/astrocommunity/blob/bb8089b72bbb11ad850902ce58a9f1fc64277563/lua/astrocommunity/pack/go/init.lua#L134-L142

2024-08-17 09:06 UTC, Uzaaft requested changes
Could you add them to the docs as Well

2024-08-17 10:19 UTC, Uzaaft commented
actually, we should do the opposite

2024-08-17 13:34 UTC, Uzaaft commented
We should remove these from conform.

2024-08-17 20:37 UTC, pgr0ss commented
Why do you think we should remove them from conform instead of installing them?

2024-08-18 07:51 UTC, Uzaaft commented
> Why do you think we should remove them from conform instead of installing them?

Because we removed them from the null-ls portion. We should remove them from conform as Well.

2024-08-19 05:06 UTC, pgr0ss commented
Sorry, I don't think I understand. `goimports` in particular is extremely useful, and I don't think we want to remove it. I think we want auto imports by default. I have less of an opinion on`gofumpt`, however. I have been using it and like it, but I think it's also ok if the go pack defaults to using the standard formatter. Thanks.

2024-08-19 05:13 UTC, Uzaaft commented
> think

It's already removed in the pack. The conform stuff is just dangling because it wasn't removed with the null-ls stuff

2024-08-19 13:12 UTC, mehalter commented
Opened up a new PR that amends this commit. Thanks for catching this! `goimports` was removed on accident :D

2024-08-19 13:12 UTC, closed without merging

2024-08-19 14:24 UTC, Uzaaft commented
> Opened up a new PR that amends this commit. Thanks for catching this! `goimports` was removed on accident :D

I wonder who removed them...👀