feat(docker): Add `lazydocker.nvim`
AstroNvim/astrocommunity pull request #1176
Opened 2024-08-22 18:35 UTC by Mourishitz

## 📑 Description

Adds [Lazy Docker](https://github.com/mgierada/lazydocker.nvim) package to the AstroNvim community.

## ℹ Additional Information

This PR adds a new shortcut to `Leader + t` + `d` which runs the Lazy Docker plugin.
It depends only on [lazydocker.nvim](https://github.com/mgierada/lazydocker.nvim) and it uses built-in ToggleTerm support.

No breaking changes or old behavior interference.

![image](https://github.com/user-attachments/assets/01cc5291-c4cd-487f-b1bd-51fb962a875f)

2024-08-22 20:35 UTC, Uzaaft commented on lua/astrocommunity/docker/lazydocker/init.lua
> +    config = function() require("lazydocker").setup {} end,
```suggestion
    config = function() require("lazydocker").setup {} end,
```
This is not needed. Use opts instead.

2024-08-22 20:35 UTC, Uzaaft requested changes
See comment

2024-08-24 02:42 UTC, Mourishitz commented
Got it!! Tested it out and still runs smooth and perfect! Thanks for the suggestion

2024-08-24 11:51 UTC, Uzaaft commented on lua/astrocommunity/docker/lazydocker/init.lua
> +    },
```suggestion
    opts = {},
```

2024-08-24 11:52 UTC, Uzaaft commented on lua/astrocommunity/docker/lazydocker/init.lua
> +              [prefix .. "d"] = {
```suggestion
              ["<Leader>t" .. "d"] = {
```

2024-08-24 11:52 UTC, Uzaaft commented on lua/astrocommunity/docker/lazydocker/init.lua
> +local prefix = "<Leader>t"
```suggestion
```

2024-08-24 11:53 UTC, Uzaaft commented
You still didnt use it correctly. Test out the new plugin spec @Mourishitz

2024-08-24 23:26 UTC, Mourishitz commented
Yes it seems to work really well! Thanks for the suggestions, its my first contribution to astro community and I'm not used to the best practices yet

2024-08-25 08:27 UTC, Uzaaft approved these changes

2024-08-25 08:28 UTC, merged