feat(utility): add `harper-ls` integration
AstroNvim/astrocommunity pull request #1199
Opened 2024-09-09 14:10 UTC by cristobalgvera

## 📑 Description

Add [`harper-ls`](https://github.com/elijah-potter/harper/tree/master/harper-ls) integration, a `LSP` to interop with [Harper](https://writewithharper.com).

## ℹ Additional Information

From it's website:

> Harper is an English grammar checker designed to be just right. You can think of it as an open-source alternative to Grammarly.

2024-09-13 09:23 UTC, mehalter requested changes
Thanks for the contribution! This should be a language pack that goes in `lua/astrocommunity/pack/harper.lua` since it configures multiple plugins at once time and also is not providing a new plugin.

2024-09-13 09:25 UTC, mehalter reviewed
This block should be moved up to a top level spec rather than a dependency. If the user has disabled Mason, the spec should still apply the recommended settings to the language server

2024-09-13 18:56 UTC, cristobalgvera commented on lua/astrocommunity/utility/harper-ls/init.lua
> +      },
Thanks for this comment, I didn't know about it!

2024-09-13 18:56 UTC, cristobalgvera commented
> Thanks for the contribution! This should be a language pack that goes in `lua/astrocommunity/pack/harper.lua` since it configures multiple plugins at once time and also is not providing a new plugin.

Moved!

2024-09-16 00:23 UTC, mehalter requested changes
Thanks so much! Only thing is it should be `pack/harper` and not `pack/harper-ls`

2024-09-16 00:27 UTC, mehalter approved these changes
I went ahead and fixed it to get this merged. Thanks again!

2024-09-16 00:27 UTC, merged