Feature/update autosave nvim repo
AstroNvim/astrocommunity pull request #1239
Opened 2024-10-11 06:03 UTC by ALameLlama

Closes #1233

## 📑 Description

Updates to use actively maintained okuuva repo, I also needed to update the way the callbacks work. These are currently broken since it's using autoformat_enabled instead of autoformat

2024-10-11 06:06 UTC, ALameLlama commented
I'll still need to do a little more testing, but this should be a drop in replacement to the old callbacks and actually work since before they used the wrong vim options

2024-10-13 10:04 UTC, Uzaaft commented on lua/astrocommunity/editing-support/auto-save-nvim/init.lua
> +})
this should be done using astrocore

2024-10-13 10:05 UTC, Uzaaft commented on lua/astrocommunity/editing-support/auto-save-nvim/init.lua
> +})
Also why was this moved outside the original plugin spec?

2024-10-13 10:05 UTC, Uzaaft submitted a review, later dismissed
see comments

2024-10-13 10:06 UTC, Uzaaft requested changes
See comments

2024-10-13 12:08 UTC, ALameLlama commented
@Uzaaft Done 🫡.  Moved to use astro core autocmds and everything still seems to be working

2024-10-17 12:19 UTC, ALameLlama commented
I also might need to update the title of this PR to include that it's a breaking change.

the forked repo is a drop-in replacement if it's just the defaults but if people have extended it, it might break things

2024-10-23 10:33 UTC, Uzaaft approved these changes

2024-10-23 10:33 UTC, merged