feat(editing-support): add cutlass-nvim
AstroNvim/astrocommunity pull request #174
Opened 2023-05-01 16:26 UTC by owittek

2023-05-01 17:51 UTC, mehalter requested changes
new `list_insert_unique` syntax

2023-05-01 17:51 UTC, mehalter commented on lua/astrocommunity/editing-support/cutlass-nvim/cutlass-nvim.lua
> +      utils.list_insert_unique(opts.exclude, { "ns", "nS" })
```suggestion
      opts.exclude = utils.list_insert_unique(opts.exclude, { "ns", "nS" })
```

2023-05-01 17:56 UTC, mehalter requested changes
gotta get them style points :eyes:

2023-05-01 18:00 UTC, mehalter approved these changes
LGTM

2023-05-01 18:00 UTC, merged

2023-05-02 10:00 UTC, utkarshgupta137 commented
@owittek, is it working for you? Cutlass only works for me if I set `lazy = false`?

2023-05-02 10:02 UTC, owittek commented
> @owittek, is it working for you? Cutlass only works for me if I set `lazy = false`.

Yep it works for me. I've set the "User AstroFile" event to load the plugin which triggers as soon as you enter a buffer.

2023-05-12 14:19 UTC, utkarshgupta137 commented
Maybe it's because I use `neovim-session-manager` to load currdir session on startup, but it doesn't work for me unless I add `lazy = false`.

2023-09-11 09:21 UTC, sebastianst commented
@owittek it doesn't work for me. The `d` commands still save the deleted text to the yank register, as if another plugin is restoring the changes to the `d` bindings by cutlass. I confirmed that the plugin actually loads (with `:Lazy`), and the `cut_key` option also works and binds e.g. `mm` as expected. I don't have much other custom configuration. Any ideas what could be wrong?

2023-09-11 09:31 UTC, sebastianst commented
I found the culprit: which-key. Disabling it makes cutlass work again.
See also https://github.com/gbprod/cutlass.nvim/issues/20 and https://github.com/folke/which-key.nvim/issues/513
However, the bug reporter there only has the issue that which-key doesn't pop up when pressing `d`. In my case, which-key does pop up, but cutlass just doesn't work at all. Seems like an ordering issue.