feat(pack): adds angular pack
AstroNvim/astrocommunity pull request #254
Opened 2023-06-02 22:30 UTC by axelcalixte

Hello,

I noticed there wasn't any pack for Angular so I made one for myself.
Maybe it is useful to someone else.

2023-06-03 10:39 UTC, luxus commented
does it make sense that it depends on the ts pack? @owittek @Uzaaft

2023-06-03 10:54 UTC, Uzaaft commented
I don't think so. I remember mehalter voting against it whenever @owittek  did it in the deno pack.

2023-06-03 11:33 UTC, owittek commented
I actually do the same with the all-in-one pack and since Angular is made for Node I think it's fine to depend on the default ts-pack.

2023-06-03 13:01 UTC, mehalter requested changes
LGTM! We just need to mention the angular treesitter plugin that gets installed. Is that a dependency for treesitter?

2023-06-03 14:30 UTC, owittek commented
We might want to switch the branch for the plugin as described here: https://github.com/nvim-treesitter/nvim-treesitter-angular/pull/4#issuecomment-1372982890

2023-06-03 14:56 UTC, axelcalixte commented
> LGTM! We just need to mention the angular treesitter plugin that gets installed. Is that a dependency for treesitter?

@mehalter The angular treesitter parser isn't available via `:TSInstall angular`. That's why the plugin is needed.

> We might want to switch the branch for the plugin as described here: [nvim-treesitter/nvim-treesitter-angular#4 (comment)](https://github.com/nvim-treesitter/nvim-treesitter-angular/pull/4#issuecomment-1372982890)

@owittek  I wasn't aware of this branch. Thank you !

2023-06-03 15:26 UTC, owittek approved these changes
LGTM! @Uzaaft @luxus We'll have to refactor when we add a js pack as discussed on discord

2023-06-03 15:29 UTC, mehalter commented
@owittek do you mean `js` or `html+css` web pack? I was saying on discord a minimal html+css pack without any JavaScript

2023-06-03 15:29 UTC, mehalter commented
I can do the refactor on Monday

2023-06-03 16:06 UTC, owittek commented
> @owittek do you mean `js` or `html+css` web pack? I was saying on discord a minimal html+css pack without any JavaScript 

I already replied on discord but I meant the `js pack` with a working DAP which should be added at the same time as the `html+css` web pack. I just wanted to mention it since it would have to be refactored too.

2023-06-05 06:34 UTC, owittek requested changes
Refactor to use the html-css base pack

2023-06-05 06:34 UTC, owittek commented on lua/astrocommunity/pack/angular/README.md
> +- Adds `html` and `css` Treesitter parsers
```suggestion
- Adds [HTML & CSS support](../html-css)
```

2023-06-05 06:34 UTC, owittek commented on lua/astrocommunity/pack/angular/angular.lua
> +  },
```suggestion
  { import = "astrocommunity.pack.html-css" },
  { import = "astrocommunity.pack.typescript" },
```

2023-06-05 06:34 UTC, owittek commented on lua/astrocommunity/pack/angular/angular.lua
> +  },
```suggestion
```

2023-06-05 06:34 UTC, owittek commented on lua/astrocommunity/pack/angular/angular.lua
> +    end,
```suggestion
    opts = function(_, opts) opts.ensure_installed = utils.list_insert_unique(opts.ensure_installed, "angularls") end,
```

2023-06-05 11:12 UTC, mehalter approved these changes
Did a refactor to move to using the `html-css` pack and also moved the `elgiano/nvim-treesitter-angular` to be a dependency of `nvim-treesitter`. Have tested locally and looks good to go! Thanks @axelcalixte !

2023-06-05 11:13 UTC, merged