feat(harpoon): make terminal keymaps dynamic based on $TMUX
AstroNvim/astrocommunity pull request #292
Opened 2023-06-20 10:30 UTC by RayJameson

I believe it's better when you have to remember one less keybinding.
Hope nobody gets upset because of the removed "j" keymap.
I may add it for compatibility

2023-06-20 16:20 UTC, RayJameson commented
randomly fixed the error that occurred if used canceled input when using the "go to terminal" thing, also added a new keymap to jump to the index of the mark

2023-06-20 20:39 UTC, luxus commented
anyone else that uses harpoon can confirm that?

2023-06-20 22:18 UTC, RayJameson commented
@luxus on second thought, maybe it's better to leave keymaps as they do not contradict each other. You can still make `:term` while using TMUX, maybe someone using it. And in my experience, the TMUX keymap doesn't work as intended, I checked the plugin repo there is at least one open issue:
- thePrimeagen/harpoon#180

I can remove remap part and leave everything else

2023-06-22 16:45 UTC, mehalter reviewed
Hey @RayJameson just a heads up, I went ahead and rebased this on `main` because there was a bit of standardization that was done for filenames

2023-06-22 16:46 UTC, owittek commented
> This also fixes which key preview, by adding an empty function. Before it was `<prefix><prefix>`, now it's `󱡀 Harpoon`, however I didn't figure out how to make it blue color as it should be.

Could you please elaborate what the empty function fixes exactly? Having any functionality (like an anonymous function) leads to the which-key entry not being colored.

2023-06-22 17:35 UTC, mehalter requested changes
A few small comments about more easily setting variables and small typo fix

2023-06-22 17:35 UTC, mehalter commented on lua/astrocommunity/motion/harpoon/init.lua
> +        if running_tmux_seesion then
```suggestion
        if running_tmux_session then
```

Propagate typo fix

2023-06-22 17:46 UTC, mehalter approved these changes
LGTM!

2023-06-22 17:47 UTC, mehalter commented
@RayJameson I think the last thing before we merge, is do you think you could come up with a good way to word the fact that there are binding changes from this commit? I think that would take higher precedence than the dynamic changing of the text in the message

2023-06-22 18:03 UTC, RayJameson commented
@mehalter done

2023-06-22 18:06 UTC, merged

2023-06-22 18:06 UTC, mehalter commented
Thanks for your work on this @RayJameson ! ❤️