feat(editing-support): add ultimate-autopair.nvim
AstroNvim/astrocommunity pull request #314
Opened 2023-06-25 03:21 UTC by windowsrefund

2023-06-25 11:52 UTC, luxus commented on lua/astrocommunity/editing-support/ultimate-autopair-nvim/init.lua
> +    lazy = false,
why did you turn of lazy?

2023-06-25 12:24 UTC, Uzaaft commented
@windowsrefund I think the opts should be empty, unless there's a reason why you're setting changing them.

2023-06-29 19:32 UTC, mehalter requested changes
Oh, this README.md file should be in the `utlimate-autopair-nvim` folder also can you make the format follow the same as other plugins? This looks like it's more following the format of the README for packs

2023-06-30 01:57 UTC, mehalter approved these changes
LGTM

2023-06-30 01:57 UTC, merged