feat(pack): Adding ansible pack
AstroNvim/astrocommunity pull request #346
Opened 2023-07-01 22:39 UTC by Sacro

2023-07-01 23:22 UTC, jay-babu commented on lua/astrocommunity/pack/ansible/init.lua
> +    opts = function(_, opts) opts.ensure_installed = utils.list_insert_unique(opts.ensure_installed, "ansible-lint") end,
you want the `null-ls` name, so it is automatically registered https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#ansiblelint

2023-07-01 23:22 UTC, jay-babu commented on lua/astrocommunity/pack/ansible/init.lua
> +    opts = function(_, opts) opts.ensure_installed = utils.list_insert_unique(opts.ensure_installed, "ansible-lint") end,
and add a mapping here: https://github.com/jay-babu/mason-null-ls.nvim/blob/73c68abdf65279e41526eb152876511a8ae84ea2/lua/mason-null-ls/mappings/source.lua#L13

2023-07-02 09:50 UTC, Sacro commented
Should be better now!

2023-07-02 10:56 UTC, mehalter commented
We should probably also add the `filetype.add` to this pack:

```lua
local function yaml_ft(path, bufnr)
    -- get content of buffer as string
    local content = vim.filetype.getlines(bufnr)
    if type(content) == "table" then content = table.concat(content, "\n") end

    -- check if file is in roles, tasks, or handlers folder
    local path_regex = vim.regex "(tasks\\|roles\\|handlers)/"
    if path_regex and path_regex:match_str(path) then return "yaml.ansible" end
    -- check for known ansible playbook text and if found, return yaml.ansible
    local regex = vim.regex "hosts:\\|tasks:"
    if regex and regex:match_str(content) then return "yaml.ansible" end

    -- return yaml if nothing else
    return "yaml"
  end

  vim.filetype.add {
    extension = {
      yml = yaml_ft,
      yaml = yaml_ft,
    },
  }
```

2023-07-02 11:02 UTC, Sacro commented
Looks good, do you want me to add that?

On Sun, 2 Jul 2023, 11:56 Micah Halter, ***@***.***> wrote:

> We should probably also add the filetype.add to this pack:
>
> local function yaml_ft(path, bufnr)
>     -- get content of buffer as string
>     local content = vim.filetype.getlines(bufnr)
>     if type(content) == "table" then content = table.concat(content, "\n") end
>
>     -- check if file is in roles, tasks, or handlers folder
>     local path_regex = vim.regex "(tasks\\|roles\\|handlers)/"
>     if path_regex and path_regex:match_str(path) then return "yaml.ansible" end
>     -- check for known ansible playbook text and if found, return yaml.ansible
>     local regex = vim.regex "hosts:\\|tasks:"
>     if regex and regex:match_str(content) then return "yaml.ansible" end
>
>     -- return yaml if nothing else
>     return "yaml"
>   end
>
>   vim.filetype.add {
>     extension = {
>       yml = yaml_ft,
>       yaml = yaml_ft,
>     },
>   }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AstroNvim/astrocommunity/pull/346#issuecomment-1616599050>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUJMHPQ7GW4OLVMEF2EEGDXOFHVDANCNFSM6AAAAAAZ3BWLYI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-07-02 11:27 UTC, mehalter commented
Oh wait, does `ansible-vim` already add this? This might not be necessary

2023-07-02 11:53 UTC, Sacro commented
It does, but it's not lazy loaded unless you manually set the filetype first. if we can trigger that automagically that would be nice.

2023-07-02 13:34 UTC, mehalter commented
@Sacro if we set the filetype and are using language servers and treesitter, does `ansible-vim` even provide anything else? I think it just provides syntax highlighting and filetype detector which are all handled elsewhere

2023-07-02 13:40 UTC, Sacro commented
I find I'm getting better code completion with it enabled.

On Sun, 2 Jul 2023, 14:34 Micah Halter, ***@***.***> wrote:

> @Sacro <https://github.com/Sacro> if we set the filetype and are using
> language servers and treesitter, does ansible-vim even provide anything
> else? I think it just provides syntax highlighting and filetype detector
> which are all handled elsewhere
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AstroNvim/astrocommunity/pull/346#issuecomment-1616662992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUJMHLJANTNQ7JMLEN5QH3XOF2GZANCNFSM6AAAAAAZ3BWLYI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-02 13:42 UTC, mehalter requested changes

2023-07-02 13:42 UTC, mehalter commented on lua/astrocommunity/pack/ansible/init.lua
> +    ft = "yaml.ansible",
```suggestion
    "pearofducks/ansible-vim",
    init = function()
      -- add vim.filetype
    end,
    ft = "yaml.ansible",
```

I think we can put the filetype add to this plugins initialization to get the lazy loading

2023-07-02 13:44 UTC, mehalter commented on lua/astrocommunity/pack/ansible/init.lua
> +    ft = "yaml.ansible",
Oh also could you add ansible-vim mention to the readme

2023-07-02 18:41 UTC, mehalter approved these changes
This looks awesome thanks!

2023-07-02 18:41 UTC, merged