Disable colorcolumn in home screen and file tree
AstroNvim/astrocommunity pull request #607
Opened 2023-10-14 23:51 UTC by menoua

## 📑 Description

Adds two filetypes (alpha, neo-tree) to the "smartcolumn" plugin's default list of disabled_filetypes (help, text, markdown). As both alpha-nvim and Neo-tree are included in the AstroNvim core and I see no reason why anyone would want a column in either case, I think it's a good idea to add them to the list of disabled filetypes.

## ℹ Additional Information

This is the current behavior:
<img width="1904" alt="Screenshot 2023-10-14 at 7 47 52 PM" src="https://github.com/AstroNvim/astrocommunity/assets/39179450/7adfb305-fb1c-401f-af53-f5746151f680">

This is after the change:
<img width="1904" alt="Screenshot 2023-10-14 at 7 46 59 PM" src="https://github.com/AstroNvim/astrocommunity/assets/39179450/3d1e250a-1755-483f-a8e9-0d0e2afbd167">

2023-10-16 04:54 UTC, Uzaaft requested changes

2023-10-16 04:54 UTC, Uzaaft commented on lua/astrocommunity/bars-and-lines/smartcolumn-nvim/init.lua
> +    disabled_filetypes = { "neo-tree", "alpha", "help", "text", "markdown" },
Could you add starter as a filetype?

2023-10-16 16:59 UTC, menoua commented on lua/astrocommunity/bars-and-lines/smartcolumn-nvim/init.lua
> +    disabled_filetypes = { "neo-tree", "alpha", "help", "text", "markdown" },
Done.

2023-10-17 16:52 UTC, Uzaaft approved these changes

2023-10-17 16:52 UTC, merged