feat(note-taking): add support for zettelkasten with zk-nvim
AstroNvim/astrocommunity pull request #654
Opened 2023-11-26 17:24 UTC by gacallea

## 📑 Description

Adding support for zk-nvim.

## ℹ Additional Information

All about Zettelkasten here: https://zettelkasten.de/posts/overview/

2023-11-26 20:30 UTC, Uzaaft requested changes
plugin spec seems alright, please take a look at the changes I suggest for the docs

2023-11-26 20:30 UTC, Uzaaft commented on lua/astrocommunity/note-taking/zk-nvim/README.md
> +- automatically attach buffers in a zk notebook that match the given filetypes
This should be:
```suggestion
# zk-nvim

Neovim extension for the [zk](https://github.com/mickael-menu/zk) plain text note-taking assistant.

**Repository:** <https://github.com/mickael-menu/zk-nvim>

> :warning: This plugin will setup and start the LSP server for you, do *not* call `require("lspconfig").zk.setup()`.


```

2023-11-27 08:59 UTC, Uzaaft approved these changes

2023-11-27 09:02 UTC, Uzaaft commented on lua/astrocommunity/note-taking/zk-nvim/init.lua
> +    end,
```suggestion
    opts = {
    	picker = "telescope"
    },
 
```

2023-11-27 09:03 UTC, Uzaaft commented on lua/astrocommunity/note-taking/zk-nvim/init.lua
> +
```suggestion
```

2023-11-27 09:05 UTC, Uzaaft approved these changes

2023-11-27 09:06 UTC, gacallea commented
@Uzaaft sorry about the opts = {} missing and the style mishaps.

2023-11-27 09:06 UTC, Uzaaft commented
> @Uzaaft sorry about the opts = {} missing and the style mishaps.

I believe I fucked up the style 🤣

2023-11-27 09:06 UTC, merged