fix(harpoon): Update to v2
AstroNvim/astrocommunity pull request #741
Opened 2024-01-29 01:04 UTC by luxus

wip

2024-02-12 02:14 UTC, luxus commented
it should work now

2024-02-12 08:41 UTC, Uzaaft commented
@luxus  I’ll take a look in about 1h. 👀

2024-02-12 15:15 UTC, Uzaaft commented on lua/astrocommunity/motion/harpoon/init.lua
>      cmd = { "Harpoon" },
```suggestion
    cmd = { "Harpoon" },
```
The command Harpoon isn't exposed by the plugin

2024-02-12 15:18 UTC, Uzaaft requested changes

2024-02-12 15:18 UTC, Uzaaft commented on lua/astrocommunity/motion/harpoon/init.lua
>      cmd = { "Harpoon" },
```suggestion
```
The command Harpoon isn't exposed by the plugin

2024-02-12 15:19 UTC, Uzaaft approved these changes

2024-02-12 15:20 UTC, merged

2024-02-15 17:11 UTC, mehalter commented
This was incorrectly not marked as a breaking change

2024-02-15 17:12 UTC, mehalter commented
just a heads up. I will revise the commit now before we tag a release