perf: set appropiate/missing lazy loading events
AstroNvim/astrocommunity pull request #856
Opened 2024-04-09 19:07 UTC by manuuurino

## 📑 Description

Noticed some lazy loading improvements from my personal config. These were the one i am using, sorry but i cannot check all plugins, i hope i can improve the startup/running performance a tiny bit further.

2024-04-09 20:01 UTC, Uzaaft commented on lua/astrocommunity/pack/yaml/init.lua
> +    ft = { "yaml", "json" },
Shouldn't toml also be added?

2024-04-09 20:02 UTC, Uzaaft commented on lua/astrocommunity/pack/yaml/init.lua
> +    ft = { "yaml", "json" },
My bad, taplo has it built in by default.

2024-04-09 22:01 UTC, luxus commented on lua/astrocommunity/editing-support/true-zen-nvim/init.lua
will it not get loaded when using the mappings?

2024-04-09 22:03 UTC, mehalter requested changes
A few of these need to be reverted because they are significantly less performant. Other than that, thanks for the recommendations!

2024-04-09 22:03 UTC, mehalter commented on lua/astrocommunity/editing-support/true-zen-nvim/init.lua
> +  event = "VeryLazy",
```suggestion
```



This should not be lazy loaded on event. It is lazy loaded on module and keybinding

2024-04-09 22:03 UTC, mehalter commented on lua/astrocommunity/editing-support/vim-move/init.lua
> +  event = "User AstroFile",
```suggestion
  event = { "User AstroFile", "InsertEnter" },
```

This lets it work on new files as well

2024-04-09 22:03 UTC, mehalter commented on lua/astrocommunity/lsp/lsp-inlayhints-nvim/init.lua
> +    event = "User AstroLspSetup",
```suggestion
```

This lazy loading is handled by the autocmd and should not be loaded on event. This is less performant

2024-04-09 22:03 UTC, mehalter commented on lua/astrocommunity/pack/yaml/init.lua
> +    ft = { "yaml", "json" },
```suggestion
    lazy = true,
```

this should be reverted. This is more performant as is. It is lazy loaded based on module only when needed.

2024-04-10 06:53 UTC, mehalter approved these changes
I went in and resolved the performance issues. Thanks!

2024-04-10 06:54 UTC, merged