feat(lsp): add `nvim-context-vt`
AstroNvim/astrocommunity pull request #858
Opened 2024-04-09 19:22 UTC by manuuurino

2024-04-09 19:41 UTC, Uzaaft commented on lua/astrocommunity/lsp/nvim-context-vt/init.lua
> +  event = "User AstroFile",
```suggestion
  event = "User AstroFile",
  cmd = {"NvimContextVtToggle"},
```

2024-04-09 19:41 UTC, Uzaaft requested changes
The cmd should be added

2024-04-09 19:54 UTC, Uzaaft approved these changes

2024-04-09 19:57 UTC, Uzaaft commented
@manuuurino  This plugin should be in editing-support imo.

2024-04-10 07:24 UTC, mehalter approved these changes

2024-04-10 07:24 UTC, merged