feat(code-runner): added the toggletasks.nvim plugin
AstroNvim/astrocommunity pull request #965
Opened 2024-05-14 15:57 UTC by vbmaarten

## 📑 Description

added the toggletasks.nvim plugin

## ℹ Additional Information

2024-05-14 18:07 UTC, mehalter requested changes

2024-05-14 18:07 UTC, mehalter commented on lua/astrocommunity/code-runner/toggletasks-nvim/init.lua
> +  init = function() require("telescope").load_extension "toggletasks" end,
```suggestion
  init = function()
    require("astrocore").on_load("telescope.nvim", function() require("telescope").load_extension "toggletasks" end)
  end,
```

respect the lazy loading of telescope

2024-05-14 18:07 UTC, mehalter commented on lua/astrocommunity/code-runner/toggletasks-nvim/init.lua
> +    { "nvim-telescope/telescope.nvim" },
```suggestion
    { "nvim-telescope/telescope.nvim" },
    {
      "AstroNvim/astrocore",
      opts = {
        mappings = {
          n = {
            ["<Leader>tss"] = { "<Cmd>Telescope toggletasks spawn<CR>", desc = "toggletasks: spawn" },
            ["<Leader>tsc"] = { "<Cmd>Telescope toggletasks select<CR>", desc = "toggletasks: select" },
            ["<Leader>tse"] = { "<Cmd>Telescope toggletasks edit<CR>", desc = "toggletasks: edit config" },
          },
        },
      },
    },
```

map keys with AstroCore

2024-05-15 08:01 UTC, mehalter approved these changes

2024-05-15 08:05 UTC, vbmaarten commented
Suggestions have been applied, and the result has been tested locally

2024-05-15 08:13 UTC, mehalter requested changes
Last thing, thanks so much! I forget, I don't think `init` implies lazy = true in lazy.nvim

2024-05-15 08:21 UTC, vbmaarten commented
> Last thing, thanks so much! I forget, I don't think `init` implies lazy = true in lazy.nvim

Applied and tested 👍

2024-05-15 08:30 UTC, mehalter approved these changes

2024-05-15 08:30 UTC, merged